#baseURL = "https://jfrobbins.github.io/blog" # For user/organization pages
baseURL = 'https://jrobb.org/'
languageCode = 'en-us'
title = 'jrobb.org'
theme = "hugo-theme-m10c"
publishDir = "docs"

# https://themes.gohugo.io/themes/hugo-theme-m10c/

[params]
  author = "Jon Robbins"
  description = "Just my random thoughts"
#  avatar = "https://avatars.githubusercontent.com/u/850844?v=4"
  avatar = "/images/avatars/rm/grok-me-rm-style-2.jpg"
  menu_item_separator = "<br>"
  favicon = "/favicon.ico"



[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 3
  
[[menu.main]]
  name = "Quotes"
  url = "/tags/quotes/"
  weight = 50 
  
[[menu.main]]
  name = "Guides"
  url = "/tags/guides/"
  weight = 55 

[[menu.main]]
  name = "Recipes"
  url = "/tags/recipes/"
  weight = 60

[[menu.main]]
  identifier = "about"
  name = "About Hugo"
  url = "https://gohugo.io/"
  weight = 99



[[params.social]]
  icon = "brand-mastodon"
  name = "Mastodon"
  url = "https://mastodon.social/@jrobb"

[[params.social]]
  name = "X"
  icon = "brand-x"
  url = "https://x.com/jrobbnc"

[[params.social]]
  icon = "brand-github"
  name = "My Github"
  url = "https://github.com/jfrobbins"
