#baseURL = "https://jfrobbins.github.io/blog" # For user/organization pages
baseURL = 'https://jrobb.org/'
languageCode = 'en-us'
title = 'jrobb.org'
theme = "hugo-theme-m10c"
publishDir = "docs"

# https://themes.gohugo.io/themes/hugo-theme-m10c/

[params]
  author = "Jon Robbins"
  description = "Just my random thoughts"
  avatar = "/images/avatars/rm/grok-me-rm-style-2.jpg"
  menu_item_separator = "<br>"
  favicon = "/favicon.ico"
  paginate = 20



[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 3
  
[[menu.main]]
  name = "Quotes"
  url = "/tags/quotes/"
  weight = 10 
  
[[menu.main]]
  name = "Guides"
  url = "/tags/guides/"
  weight = 20 

#[[menu.main]]
#  name = "Recipes"
#  url = "/tags/recipes/"
#  weight = 30
  
  
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 40

#[[menu.main]]
#  name = "Contact"
#  url = "/contact/"
#  weight = 50
 


[[params.social]]
  icon = "brand-mastodon"
  name = "Mastodon"
  url = "https://mastodon.social/@jrobb"

[[params.social]]
  name = "X"
  icon = "brand-x"
  url = "https://x.com/jrobbnc"

[[params.social]]
  icon = "brand-github"
  name = "My Github"
  url = "https://github.com/jfrobbins"
